sudo: required

services:
  - docker
  - postgresql

language: python
python:
  - "3.6"

env:
  global:
    - SECRET_KEY=changeme
    - DATABASE_URL=postgresql://postgresql@localhost/travis_db

before_script:
  - psql -c 'create database travis_db;' -U postgres
  - docker build -t urunscope:latest .

script:
  - docker run --network host -e SECRET_KEY -e DATABASE_URL urunscope:latest pytest

