# Generated by Django 2.0 on 2017-12-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0003_training_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
