# Generated by Django 2.0 on 2017-12-27 23:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0004_auto_20171223_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='hrm',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
